apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  namespace: yac
  labels:
    app: coordinator
spec:
  replicas: 12
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
      - name: coordinator
        image: abrevnov/yac
        imagePullPolicy: Always
        ports:
        - containerPort: 8080